### ISSUE TITLE
Licence of syslog-mode

### ISSUE THREAD

**Issue by brandelune** [vapniks/syslog-mode#15]
Hi,

In a thread in the emacs-devel maillist, the licensing situation for emacs packages provided through Emacs package archives has been under focus. I have volunteered to contact the authors of packages that have a license that is incompatible with Emacs, which is now under GPL-3+.

See https://lists.gnu.org/archive/html/emacs-devel/2017-07/msg01069.html

So I wonder if you could consider to change the license of your package to GPL-3+?

Yours,

Jean-Christophe Helary

**Comment by tarsius** [comment]
Friendly ping :wink:

**Comment by tarsius** [comment]
This package had to be removed from Melpa. If you update the GPL, then it can be added back.

**Comment by vapniks** [comment]
I am not the original author so I don't think I have the right to change the license, or do I?

**Comment by tarsius** [comment]
All contributors have to agree I am afraid.

**Comment by brandelune** [comment]
Besides for the original author: Harley Gorrell <harley@mahalito.net> and all the currently identified contributors, are there other people you are aware of ?

**Comment by vapniks** [comment]
No.

**Comment by brandelune** [comment]
Wold you mind asking all the people who are involved ?

**Comment by vapniks** [comment]
I just sent out an email.

**Comment by brandelune** [comment]
Thank you so much ! Let us know here when you have a common agreement !

**Comment by technician77** [comment]
Any update on this? I really would like to see this back on melpa. After testing other "solutions" it dawned on me that this is still the best.

**Comment by vapniks** [comment]
I emailled 6 of the contributors about changing the license, but only heard back from 2 of them (who both consented).

**Comment by technician77** [comment]
The mail you sent a year ago? Did you retry?

**Comment by vapniks** [comment]
I just resent it now.

**Comment by technician77** [comment]
Nothing? Can the package be "rewritten" to solve this?

**Comment by vapniks** [comment]
You're free to.. ahem.. write your own version.. but I don't know how different it needs to be for it to be accepted into melpa. What do you think @tarsius ?

**Comment by tarsius** [comment]
Has the original author agreed to the change? If not, then you can forget it.

Otherwise it doesn't look that bad:

```
     1  Alex Kost
     2  Andrey Tykhonov
     1  Arne Jørgensen
     1  Emanuele Tomasi
    76  Joe Bloggs
     1  Russell Sim
     6  vapniks
```

Joe Bloggs is @vapniks. So:

```
     1  Alex Kost
     2  Andrey Tykhonov
     1  Arne Jørgensen
     1  Emanuele Tomasi
     1  Russell Sim
```

And at least one of them has agreed? Who?

Since you have only emailed these people so far we should ask there right here on Github before doing anything else.

@atykhonov @targzeta @russell @arnested @alezost `syslog-mode` which is currently licensed under the GPL version 2 (exactly that version, NOT "... or (at your option) any later version") has to be relicensed to "GPL version 3, or (at your option) any later version" to make it compatible with the license used by GNU Emacs itself. You have contributed to this package. Do you agree with this change?

If one of these contributors declines or does not respond, then we can start removing their contributions.

I have already looked at all the `git log -u --author="AUTHOR"` and all the contributions are minor. If we need to, it would be easy to remove them. And then asking *someone else* to redo them without looking at the old implementation. One such todo item for example would read: "The faces are being defined using `defcustom`. As we all know that is wrong. Do it using `defface`."

**Comment by alezost** [comment]
I agree, please do it.

**Comment by russell** [comment]
I also agree, I see that Arne Jørgensen also replied to the email

**Comment by arnested** [comment]
I agree as well.

**Comment by targzeta** [comment]
I agree as well.

**Comment by tarsius** [comment]
We are getting close.

@vapniks Could you please let us know whether Harley Gorrell has agreed?

Harley Gorrell might or might not be @harley-gorrell.

**Comment by vapniks** [comment]
I didn't get any reply from either Harley Gorrell (harley@mahalito.net), nor Andrey Tykhonov (atykhonov@gmail.com).

**Comment by technician77** [comment]
Without Harley this thing is dead as a stick, isn't it? One might remove Andreys contributions but without the original author more or less the whole code is locked. I tried to contact him via facebook, since his website looks abandoned to me, but no reply as of yet.

**Comment by jhgorrell** [comment]
Hello! Sorry for the delay. I am ok with the change to GPLv3.
Can get that done shortly.

**Comment by brandelune** [comment]
Please see message https://github.com/vapniks/syslog-mode/issues/15#issuecomment-504012745 above !

**Comment by jhgorrell** [comment]
Gave it a read and it sounds like all I have to do is to agree. (which I do!)
Should I make a PR to change the licence?

**Comment by tarsius** [comment]
> Should I make a PR to change the licence?

Yes please.

But base it on [my `master` branch](https://github.com/emacsjanitors/syslog-mode). That has two extra commit which remove contributions by Andrey Tykhonov who still has not agreed to the license change.

----

Later someone else should redo these changes **without looking at any old commits**:

1. There are whitespace errors. Fix them.
2. There is an undocumented variable that isn't being used for anything. Remove it.
3. Create a command that shows a message about how many matches there are for a regexp read from the user. *Actually*, don't. That doesn't sound useful. (At least not to me. Then again I don't use this mode, so what do I know.)

**Comment by jhgorrell** [comment]
PR: https://github.com/emacsjanitors/syslog-mode/pull/1

**Comment by tarsius** [comment]
I wasn't clear. I meant: Create a pull-request in this repository `vapniks/syslog-mode` but also include the two reverting commits that I authored, which you can find in the `master` branch of `emacsjanitors/syslog-mode` because that way you don't change the license for a version of this package which contains changes for which you are not actually in a position to change the license (the changes by Andrey who did not agree to the license change).

**Comment by tarsius** [comment]
Of course @vapniks can also my two and @jhgorrell's one commit without waiting for a pull-request.

**Comment by jhgorrell** [comment]
Ok - removed the old PR, (https://github.com/emacsjanitors/syslog-mode/pull/1)
and did a new one to vapniks/syslog-mode. (https://github.com/vapniks/syslog-mode/pull/16)

**Comment by vapniks** [comment]
OK, I have the pull-request from @jhgorrell  for the licence change. @tarsius could you make a pull-request to this repo with your 2 reverting commits?

**Comment by tarsius** [comment]
I've added it to Melpa and the Emacsmirror again.

I think we are done here. :champagne:

**Comment by tarsius** [comment]
Thanks everyone!

**Comment by technician77** [comment]
Thanks to everyone who contributed to bring this mode back to melpa. The mode is too useful not be on melpa.
